//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itbeard.Site.WebAssembly.Localizations.Pages.Projects {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BeardNews {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BeardNews() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Itbeard.Site.WebAssembly.Localizations.Pages.Projects.BeardNews", typeof(BeardNews).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        internal static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        internal static string About_Web {
            get {
                return ResourceManager.GetString("About_Web", resourceCulture);
            }
        }
        
        internal static string About_How {
            get {
                return ResourceManager.GetString("About_How", resourceCulture);
            }
        }
        
        internal static string About_Paragraph_1 {
            get {
                return ResourceManager.GetString("About_Paragraph_1", resourceCulture);
            }
        }
        
        internal static string About_Paragraph_2 {
            get {
                return ResourceManager.GetString("About_Paragraph_2", resourceCulture);
            }
        }
        
        internal static string About_Paragraph_3_2 {
            get {
                return ResourceManager.GetString("About_Paragraph_3_2", resourceCulture);
            }
        }
        
        internal static string About_Paragraph_3_1 {
            get {
                return ResourceManager.GetString("About_Paragraph_3_1", resourceCulture);
            }
        }
        
        internal static string About_Paragraph_4_1 {
            get {
                return ResourceManager.GetString("About_Paragraph_4_1", resourceCulture);
            }
        }
        
        internal static string About_Paragraph_4_2 {
            get {
                return ResourceManager.GetString("About_Paragraph_4_2", resourceCulture);
            }
        }
        
        internal static string About_Paragraph_5 {
            get {
                return ResourceManager.GetString("About_Paragraph_5", resourceCulture);
            }
        }
        
        internal static string About_Links_PatreonAudio {
            get {
                return ResourceManager.GetString("About_Links_PatreonAudio", resourceCulture);
            }
        }
        
        internal static string About_Links_PatreonVideo {
            get {
                return ResourceManager.GetString("About_Links_PatreonVideo", resourceCulture);
            }
        }
        
        internal static string About_Links_Discord {
            get {
                return ResourceManager.GetString("About_Links_Discord", resourceCulture);
            }
        }
        
        internal static string About_Links_YouTube_Link {
            get {
                return ResourceManager.GetString("About_Links_YouTube_Link", resourceCulture);
            }
        }
    }
}
