//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itbeard.Site.WebAssembly.Localizations.Pages.Projects {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EvoCoders {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EvoCoders() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Itbeard.Site.WebAssembly.Localizations.Pages.Projects.EvoCoders", typeof(EvoCoders).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string ClubName {
            get {
                return ResourceManager.GetString("ClubName", resourceCulture);
            }
        }
        
        internal static string ClubDescription {
            get {
                return ResourceManager.GetString("ClubDescription", resourceCulture);
            }
        }
        
        internal static string ClubTheses {
            get {
                return ResourceManager.GetString("ClubTheses", resourceCulture);
            }
        }
        
        internal static string Thesis1 {
            get {
                return ResourceManager.GetString("Thesis1", resourceCulture);
            }
        }
        
        internal static string Thesis2 {
            get {
                return ResourceManager.GetString("Thesis2", resourceCulture);
            }
        }
        
        internal static string Thesis3 {
            get {
                return ResourceManager.GetString("Thesis3", resourceCulture);
            }
        }
        
        internal static string Thesis4 {
            get {
                return ResourceManager.GetString("Thesis4", resourceCulture);
            }
        }
        
        internal static string ClubGoalLabel {
            get {
                return ResourceManager.GetString("ClubGoalLabel", resourceCulture);
            }
        }
        
        internal static string ClubGoal {
            get {
                return ResourceManager.GetString("ClubGoal", resourceCulture);
            }
        }
        
        internal static string ClubMissionLabel {
            get {
                return ResourceManager.GetString("ClubMissionLabel", resourceCulture);
            }
        }
        
        internal static string ClubMission {
            get {
                return ResourceManager.GetString("ClubMission", resourceCulture);
            }
        }
        
        internal static string BenefitsTitle {
            get {
                return ResourceManager.GetString("BenefitsTitle", resourceCulture);
            }
        }
        
        internal static string BenefitsDescription {
            get {
                return ResourceManager.GetString("BenefitsDescription", resourceCulture);
            }
        }
        
        internal static string BenefitsListLabel {
            get {
                return ResourceManager.GetString("BenefitsListLabel", resourceCulture);
            }
        }
        
        internal static string Benefit1 {
            get {
                return ResourceManager.GetString("Benefit1", resourceCulture);
            }
        }
        
        internal static string Benefit2 {
            get {
                return ResourceManager.GetString("Benefit2", resourceCulture);
            }
        }
        
        internal static string Benefit3 {
            get {
                return ResourceManager.GetString("Benefit3", resourceCulture);
            }
        }
        
        internal static string Benefit4 {
            get {
                return ResourceManager.GetString("Benefit4", resourceCulture);
            }
        }
        
        internal static string Benefit5 {
            get {
                return ResourceManager.GetString("Benefit5", resourceCulture);
            }
        }
        
        internal static string HowItWorksTitle {
            get {
                return ResourceManager.GetString("HowItWorksTitle", resourceCulture);
            }
        }
        
        internal static string HowItWorksDescription1 {
            get {
                return ResourceManager.GetString("HowItWorksDescription1", resourceCulture);
            }
        }
        
        internal static string HowItWorksDescription2 {
            get {
                return ResourceManager.GetString("HowItWorksDescription2", resourceCulture);
            }
        }
        
        internal static string HowItWorksDescription3 {
            get {
                return ResourceManager.GetString("HowItWorksDescription3", resourceCulture);
            }
        }
        
        internal static string OpenResourcesLabel {
            get {
                return ResourceManager.GetString("OpenResourcesLabel", resourceCulture);
            }
        }
        
        internal static string YouTubeChannel {
            get {
                return ResourceManager.GetString("YouTubeChannel", resourceCulture);
            }
        }
        
        internal static string YouTubeChannelDescription {
            get {
                return ResourceManager.GetString("YouTubeChannelDescription", resourceCulture);
            }
        }
        
        internal static string GitHubRepositoryLabel {
            get {
                return ResourceManager.GetString("GitHubRepositoryLabel", resourceCulture);
            }
        }
        
        internal static string GitHubRepository {
            get {
                return ResourceManager.GetString("GitHubRepository", resourceCulture);
            }
        }
        
        internal static string GitHubRepositoryDescription {
            get {
                return ResourceManager.GetString("GitHubRepositoryDescription", resourceCulture);
            }
        }
        
        internal static string HowToGetInTitle {
            get {
                return ResourceManager.GetString("HowToGetInTitle", resourceCulture);
            }
        }
        
        internal static string SubscriptionLabel {
            get {
                return ResourceManager.GetString("SubscriptionLabel", resourceCulture);
            }
        }
        
        internal static string SubscriptionDescription {
            get {
                return ResourceManager.GetString("SubscriptionDescription", resourceCulture);
            }
        }
        
        internal static string BuyMonthlySubscription {
            get {
                return ResourceManager.GetString("BuyMonthlySubscription", resourceCulture);
            }
        }
        
        internal static string BuyAnnualSubscription {
            get {
                return ResourceManager.GetString("BuyAnnualSubscription", resourceCulture);
            }
        }
        
        internal static string PaymentOptions {
            get {
                return ResourceManager.GetString("PaymentOptions", resourceCulture);
            }
        }
        
        internal static string PaymentService {
            get {
                return ResourceManager.GetString("PaymentService", resourceCulture);
            }
        }
        
        internal static string CommunityActivitiesLabel {
            get {
                return ResourceManager.GetString("CommunityActivitiesLabel", resourceCulture);
            }
        }
        
        internal static string CommunityActivitiesDescription {
            get {
                return ResourceManager.GetString("CommunityActivitiesDescription", resourceCulture);
            }
        }
        
        internal static string ContentExamplesTitle {
            get {
                return ResourceManager.GetString("ContentExamplesTitle", resourceCulture);
            }
        }
        
        internal static string WorkshopTitle {
            get {
                return ResourceManager.GetString("WorkshopTitle", resourceCulture);
            }
        }
        
        internal static string InterviewTitle {
            get {
                return ResourceManager.GetString("InterviewTitle", resourceCulture);
            }
        }
        
        internal static string SituationalAwarenessTitle {
            get {
                return ResourceManager.GetString("SituationalAwarenessTitle", resourceCulture);
            }
        }
        
        internal static string DigestExampleTitle {
            get {
                return ResourceManager.GetString("DigestExampleTitle", resourceCulture);
            }
        }
        
        internal static string ForCompaniesTitle {
            get {
                return ResourceManager.GetString("ForCompaniesTitle", resourceCulture);
            }
        }
        
        internal static string ForCompaniesDescription {
            get {
                return ResourceManager.GetString("ForCompaniesDescription", resourceCulture);
            }
        }
        
        internal static string ForCompaniesBenefitsLabel {
            get {
                return ResourceManager.GetString("ForCompaniesBenefitsLabel", resourceCulture);
            }
        }
        
        internal static string ForCompaniesBenefit1 {
            get {
                return ResourceManager.GetString("ForCompaniesBenefit1", resourceCulture);
            }
        }
        
        internal static string ForCompaniesBenefit2 {
            get {
                return ResourceManager.GetString("ForCompaniesBenefit2", resourceCulture);
            }
        }
        
        internal static string ForCompaniesBenefit3 {
            get {
                return ResourceManager.GetString("ForCompaniesBenefit3", resourceCulture);
            }
        }
        
        internal static string ForCompaniesBenefit4 {
            get {
                return ResourceManager.GetString("ForCompaniesBenefit4", resourceCulture);
            }
        }
        
        internal static string ForCompaniesContactLabel {
            get {
                return ResourceManager.GetString("ForCompaniesContactLabel", resourceCulture);
            }
        }
    }
}