//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itbeard.Site.WebAssembly.Localizations.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CiomnyLosShow {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CiomnyLosShow() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Itbeard.Site.WebAssembly.Localizations.Pages.CiomnyLosShow", typeof(CiomnyLosShow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        internal static string About_Paragrarh_1 {
            get {
                return ResourceManager.GetString("About_Paragrarh_1", resourceCulture);
            }
        }
        
        internal static string About_Paragrarh_21 {
            get {
                return ResourceManager.GetString("About_Paragrarh_21", resourceCulture);
            }
        }
        
        internal static string About_Paragrarh_22 {
            get {
                return ResourceManager.GetString("About_Paragrarh_22", resourceCulture);
            }
        }
        
        internal static string WhereToSee {
            get {
                return ResourceManager.GetString("WhereToSee", resourceCulture);
            }
        }
        
        internal static string WhereToSee_Paragraph_1 {
            get {
                return ResourceManager.GetString("WhereToSee_Paragraph_1", resourceCulture);
            }
        }
        
        internal static string WhereToSee_Paragraph_2 {
            get {
                return ResourceManager.GetString("WhereToSee_Paragraph_2", resourceCulture);
            }
        }
        
        internal static string WhereToSee_Paragraph_3 {
            get {
                return ResourceManager.GetString("WhereToSee_Paragraph_3", resourceCulture);
            }
        }
        
        internal static string WhereToSee_Paragraph_4 {
            get {
                return ResourceManager.GetString("WhereToSee_Paragraph_4", resourceCulture);
            }
        }
        
        internal static string WhereToSee_Paragraph_6 {
            get {
                return ResourceManager.GetString("WhereToSee_Paragraph_6", resourceCulture);
            }
        }
        
        internal static string WhereToSee_Paragraph_7 {
            get {
                return ResourceManager.GetString("WhereToSee_Paragraph_7", resourceCulture);
            }
        }
        
        internal static string WhereToSee_Paragraph_8 {
            get {
                return ResourceManager.GetString("WhereToSee_Paragraph_8", resourceCulture);
            }
        }
        
        internal static string WhereToSee_Paragraph_Site {
            get {
                return ResourceManager.GetString("WhereToSee_Paragraph_Site", resourceCulture);
            }
        }
        
        internal static string Merch {
            get {
                return ResourceManager.GetString("Merch", resourceCulture);
            }
        }
        
        internal static string Merch_Paragraph_11 {
            get {
                return ResourceManager.GetString("Merch_Paragraph_11", resourceCulture);
            }
        }
        
        internal static string Merch_Paragraph_2 {
            get {
                return ResourceManager.GetString("Merch_Paragraph_2", resourceCulture);
            }
        }
        
        internal static string Merch_Paragraph_12 {
            get {
                return ResourceManager.GetString("Merch_Paragraph_12", resourceCulture);
            }
        }
        
        internal static string Merch_Paragraph_13 {
            get {
                return ResourceManager.GetString("Merch_Paragraph_13", resourceCulture);
            }
        }
        
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        internal static string Support_Patreon {
            get {
                return ResourceManager.GetString("Support_Patreon", resourceCulture);
            }
        }
        
        internal static string Support_Patreon_1 {
            get {
                return ResourceManager.GetString("Support_Patreon_1", resourceCulture);
            }
        }
        
        internal static string Support_Patreon_2 {
            get {
                return ResourceManager.GetString("Support_Patreon_2", resourceCulture);
            }
        }
        
        internal static string Support_Card {
            get {
                return ResourceManager.GetString("Support_Card", resourceCulture);
            }
        }
        
        internal static string Support_Card_1 {
            get {
                return ResourceManager.GetString("Support_Card_1", resourceCulture);
            }
        }
        
        internal static string Support_Card_2 {
            get {
                return ResourceManager.GetString("Support_Card_2", resourceCulture);
            }
        }
        
        internal static string Support_Crypto {
            get {
                return ResourceManager.GetString("Support_Crypto", resourceCulture);
            }
        }
        
        internal static string Support_Crypto_1 {
            get {
                return ResourceManager.GetString("Support_Crypto_1", resourceCulture);
            }
        }
        
        internal static string Support_Crypto_2 {
            get {
                return ResourceManager.GetString("Support_Crypto_2", resourceCulture);
            }
        }
    }
}
