//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itbeard.Site.WebAssembly.Localizations.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Contacts {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Contacts() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Itbeard.Site.WebAssembly.Localizations.Pages.Contacts", typeof(Contacts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        internal static string KeyResources {
            get {
                return ResourceManager.GetString("KeyResources", resourceCulture);
            }
        }
        
        internal static string KeyResources_Patreon {
            get {
                return ResourceManager.GetString("KeyResources_Patreon", resourceCulture);
            }
        }
        
        internal static string KeyResources_Telegram {
            get {
                return ResourceManager.GetString("KeyResources_Telegram", resourceCulture);
            }
        }
        
        internal static string Cont_Title {
            get {
                return ResourceManager.GetString("Cont_Title", resourceCulture);
            }
        }
        
        internal static string Cont_Email {
            get {
                return ResourceManager.GetString("Cont_Email", resourceCulture);
            }
        }
        
        internal static string Cont_Telegram {
            get {
                return ResourceManager.GetString("Cont_Telegram", resourceCulture);
            }
        }
        
        internal static string Cont_Mail {
            get {
                return ResourceManager.GetString("Cont_Mail", resourceCulture);
            }
        }
        
        internal static string Cont_Mail_body {
            get {
                return ResourceManager.GetString("Cont_Mail_body", resourceCulture);
            }
        }
        
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        internal static string Other_GitHub {
            get {
                return ResourceManager.GetString("Other_GitHub", resourceCulture);
            }
        }
        
        internal static string KeyResources_Itbeard {
            get {
                return ResourceManager.GetString("KeyResources_Itbeard", resourceCulture);
            }
        }
        
        internal static string KeyResources_CiomnyLos {
            get {
                return ResourceManager.GetString("KeyResources_CiomnyLos", resourceCulture);
            }
        }
        
        internal static string KeyResources_Mastodon {
            get {
                return ResourceManager.GetString("KeyResources_Mastodon", resourceCulture);
            }
        }
        
        internal static string KeyResources_Linkedin {
            get {
                return ResourceManager.GetString("KeyResources_Linkedin", resourceCulture);
            }
        }
        
        internal static string Other_Mastodon {
            get {
                return ResourceManager.GetString("Other_Mastodon", resourceCulture);
            }
        }
        
        internal static string Other_Twitter {
            get {
                return ResourceManager.GetString("Other_Twitter", resourceCulture);
            }
        }
        
        internal static string Other_Instagram {
            get {
                return ResourceManager.GetString("Other_Instagram", resourceCulture);
            }
        }
        
        internal static string Other_LinkedIn {
            get {
                return ResourceManager.GetString("Other_LinkedIn", resourceCulture);
            }
        }
    }
}
