//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itbeard.Site.WebAssembly.Localizations.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Contacts {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Contacts() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Itbeard.Site.WebAssembly.Localizations.Pages.Contacts", typeof(Contacts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        internal static string Ccontacts {
            get {
                return ResourceManager.GetString("Ccontacts", resourceCulture);
            }
        }
        
        internal static string Ccontacts_Telegram {
            get {
                return ResourceManager.GetString("Ccontacts_Telegram", resourceCulture);
            }
        }
        
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        internal static string Other_GitHub {
            get {
                return ResourceManager.GetString("Other_GitHub", resourceCulture);
            }
        }
        
        internal static string Ccontacts_Mastodon {
            get {
                return ResourceManager.GetString("Ccontacts_Mastodon", resourceCulture);
            }
        }
        
        internal static string Other_BlogFediverse {
            get {
                return ResourceManager.GetString("Other_BlogFediverse", resourceCulture);
            }
        }
        
        internal static string Other_LinkedIn {
            get {
                return ResourceManager.GetString("Other_LinkedIn", resourceCulture);
            }
        }
        
        internal static string Ccontacts_Twitter {
            get {
                return ResourceManager.GetString("Ccontacts_Twitter", resourceCulture);
            }
        }
        
        internal static string Ccontacts_Email {
            get {
                return ResourceManager.GetString("Ccontacts_Email", resourceCulture);
            }
        }
        
        internal static string Ccontacts_Discord {
            get {
                return ResourceManager.GetString("Ccontacts_Discord", resourceCulture);
            }
        }
        
        internal static string Other_Patreon {
            get {
                return ResourceManager.GetString("Other_Patreon", resourceCulture);
            }
        }
        
        internal static string Other_Merch {
            get {
                return ResourceManager.GetString("Other_Merch", resourceCulture);
            }
        }
        
        internal static string Other_BlogTelegram {
            get {
                return ResourceManager.GetString("Other_BlogTelegram", resourceCulture);
            }
        }
        
        internal static string Other_BlogWhatsapp {
            get {
                return ResourceManager.GetString("Other_BlogWhatsapp", resourceCulture);
            }
        }
    }
}
