//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itbeard.Site.WebAssembly.Localizations.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Itbeard.Site.WebAssembly.Localizations.Pages.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string AboutShow {
            get {
                return ResourceManager.GetString("AboutShow", resourceCulture);
            }
        }
        
        internal static string AboutShow_Paragraph_1 {
            get {
                return ResourceManager.GetString("AboutShow_Paragraph_1", resourceCulture);
            }
        }
        
        internal static string AboutShow_Paragraph_2 {
            get {
                return ResourceManager.GetString("AboutShow_Paragraph_2", resourceCulture);
            }
        }
        
        internal static string AboutShow_Paragraph_3 {
            get {
                return ResourceManager.GetString("AboutShow_Paragraph_3", resourceCulture);
            }
        }
        
        internal static string Interview {
            get {
                return ResourceManager.GetString("Interview", resourceCulture);
            }
        }
        
        internal static string Interview_Paragraph_1 {
            get {
                return ResourceManager.GetString("Interview_Paragraph_1", resourceCulture);
            }
        }
        
        internal static string Interview_Paragraph_1_Button {
            get {
                return ResourceManager.GetString("Interview_Paragraph_1_Button", resourceCulture);
            }
        }
        
        internal static string Profession {
            get {
                return ResourceManager.GetString("Profession", resourceCulture);
            }
        }
        
        internal static string Profession_Paragraph_1 {
            get {
                return ResourceManager.GetString("Profession_Paragraph_1", resourceCulture);
            }
        }
        
        internal static string Profession_Paragraph_1_Button {
            get {
                return ResourceManager.GetString("Profession_Paragraph_1_Button", resourceCulture);
            }
        }
        
        internal static string Programming {
            get {
                return ResourceManager.GetString("Programming", resourceCulture);
            }
        }
        
        internal static string Programming_Paragraph_1 {
            get {
                return ResourceManager.GetString("Programming_Paragraph_1", resourceCulture);
            }
        }
        
        internal static string Programming_Paragraph_1_Button {
            get {
                return ResourceManager.GetString("Programming_Paragraph_1_Button", resourceCulture);
            }
        }
        
        internal static string ExtraGoodies {
            get {
                return ResourceManager.GetString("ExtraGoodies", resourceCulture);
            }
        }
        
        internal static string ExtraGoodies_Twitter_Content {
            get {
                return ResourceManager.GetString("ExtraGoodies_Twitter_Content", resourceCulture);
            }
        }
        
        internal static string ExtraGoodies_Telegram_Content {
            get {
                return ResourceManager.GetString("ExtraGoodies_Telegram_Content", resourceCulture);
            }
        }
        
        internal static string ExtraGoodies_Instagram_Content {
            get {
                return ResourceManager.GetString("ExtraGoodies_Instagram_Content", resourceCulture);
            }
        }
        
        internal static string ExtraGoodies_Sponsorship_Title {
            get {
                return ResourceManager.GetString("ExtraGoodies_Sponsorship_Title", resourceCulture);
            }
        }
        
        internal static string ExtraGoodies_Sponsorship_Content {
            get {
                return ResourceManager.GetString("ExtraGoodies_Sponsorship_Content", resourceCulture);
            }
        }
        
        internal static string ExtraGoodies_Patreon_Title {
            get {
                return ResourceManager.GetString("ExtraGoodies_Patreon_Title", resourceCulture);
            }
        }
        
        internal static string ExtraGoodies_Patreon_Content {
            get {
                return ResourceManager.GetString("ExtraGoodies_Patreon_Content", resourceCulture);
            }
        }
        
        internal static string ExtraGoodies_Discord_Title {
            get {
                return ResourceManager.GetString("ExtraGoodies_Discord_Title", resourceCulture);
            }
        }
        
        internal static string ExtraGoodies_Discord_Content {
            get {
                return ResourceManager.GetString("ExtraGoodies_Discord_Content", resourceCulture);
            }
        }
        
        internal static string ExtraGoodies_Instagram_Title {
            get {
                return ResourceManager.GetString("ExtraGoodies_Instagram_Title", resourceCulture);
            }
        }
        
        internal static string ExtraGoodies_Twitter_Title {
            get {
                return ResourceManager.GetString("ExtraGoodies_Twitter_Title", resourceCulture);
            }
        }
        
        internal static string ExtraGoodies_Telegram_Title {
            get {
                return ResourceManager.GetString("ExtraGoodies_Telegram_Title", resourceCulture);
            }
        }
    }
}
