//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itbeard.Site.WebAssembly.Localizations.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Itbeard.Site.WebAssembly.Localizations.Pages.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        internal static string About_Paragraph_1 {
            get {
                return ResourceManager.GetString("About_Paragraph_1", resourceCulture);
            }
        }
        
        internal static string About_Paragraph_2 {
            get {
                return ResourceManager.GetString("About_Paragraph_2", resourceCulture);
            }
        }
        
        internal static string About_Paragraph_3 {
            get {
                return ResourceManager.GetString("About_Paragraph_3", resourceCulture);
            }
        }
        
        internal static string About_Paragraph_4 {
            get {
                return ResourceManager.GetString("About_Paragraph_4", resourceCulture);
            }
        }
        
        internal static string Interesting {
            get {
                return ResourceManager.GetString("Interesting", resourceCulture);
            }
        }
        
        internal static string Interesting_Merch {
            get {
                return ResourceManager.GetString("Interesting_Merch", resourceCulture);
            }
        }
        
        internal static string Interesting_Merch_Paragraph_1 {
            get {
                return ResourceManager.GetString("Interesting_Merch_Paragraph_1", resourceCulture);
            }
        }
        
        internal static string Interesting_Merch_Paragraph_2 {
            get {
                return ResourceManager.GetString("Interesting_Merch_Paragraph_2", resourceCulture);
            }
        }
        
        internal static string Interesting_Support {
            get {
                return ResourceManager.GetString("Interesting_Support", resourceCulture);
            }
        }
        
        internal static string Interesting_Support_Paragraph_1 {
            get {
                return ResourceManager.GetString("Interesting_Support_Paragraph_1", resourceCulture);
            }
        }
        
        internal static string Interesting_Support_Paragraph_2 {
            get {
                return ResourceManager.GetString("Interesting_Support_Paragraph_2", resourceCulture);
            }
        }
        
        internal static string Interesting_News {
            get {
                return ResourceManager.GetString("Interesting_News", resourceCulture);
            }
        }
        
        internal static string Interesting_News_Paragraph_2 {
            get {
                return ResourceManager.GetString("Interesting_News_Paragraph_2", resourceCulture);
            }
        }
        
        internal static string Interesting_News_Paragraph_1 {
            get {
                return ResourceManager.GetString("Interesting_News_Paragraph_1", resourceCulture);
            }
        }
        
        internal static string Interesting_GitHub {
            get {
                return ResourceManager.GetString("Interesting_GitHub", resourceCulture);
            }
        }
        
        internal static string Interesting_GitHub_Paragraph_1 {
            get {
                return ResourceManager.GetString("Interesting_GitHub_Paragraph_1", resourceCulture);
            }
        }
        
        internal static string Interesting_GitHub_Paragraph_2 {
            get {
                return ResourceManager.GetString("Interesting_GitHub_Paragraph_2", resourceCulture);
            }
        }
        
        internal static string Interesting_Where {
            get {
                return ResourceManager.GetString("Interesting_Where", resourceCulture);
            }
        }
        
        internal static string Interesting_Where_Paragrahp_1 {
            get {
                return ResourceManager.GetString("Interesting_Where_Paragrahp_1", resourceCulture);
            }
        }
        
        internal static string Interesting_Where_Paragrahp_21 {
            get {
                return ResourceManager.GetString("Interesting_Where_Paragrahp_21", resourceCulture);
            }
        }
        
        internal static string Interesting_Where_Paragrahp_22 {
            get {
                return ResourceManager.GetString("Interesting_Where_Paragrahp_22", resourceCulture);
            }
        }
        
        internal static string Interesting_Where_Paragrahp_31 {
            get {
                return ResourceManager.GetString("Interesting_Where_Paragrahp_31", resourceCulture);
            }
        }
        
        internal static string Interesting_Where_Paragrahp_32 {
            get {
                return ResourceManager.GetString("Interesting_Where_Paragrahp_32", resourceCulture);
            }
        }
        
        internal static string Interesting_Where_Paragrahp_41 {
            get {
                return ResourceManager.GetString("Interesting_Where_Paragrahp_41", resourceCulture);
            }
        }
        
        internal static string Interesting_Where_Paragrahp_42 {
            get {
                return ResourceManager.GetString("Interesting_Where_Paragrahp_42", resourceCulture);
            }
        }
        
        internal static string Interesting_LinkedIn {
            get {
                return ResourceManager.GetString("Interesting_LinkedIn", resourceCulture);
            }
        }
        
        internal static string Interesting_LinkedIn_Paragrarh_1 {
            get {
                return ResourceManager.GetString("Interesting_LinkedIn_Paragrarh_1", resourceCulture);
            }
        }
        
        internal static string Interesting_LinkedIn_Paragrarh_2 {
            get {
                return ResourceManager.GetString("Interesting_LinkedIn_Paragrarh_2", resourceCulture);
            }
        }
    }
}
