//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itbeard.Site.WebAssembly.Localizations.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Itbeard.Site.WebAssembly.Localizations.Pages.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        internal static string About_Paragraph_1 {
            get {
                return ResourceManager.GetString("About_Paragraph_1", resourceCulture);
            }
        }
        
        internal static string About_Paragraph_2 {
            get {
                return ResourceManager.GetString("About_Paragraph_2", resourceCulture);
            }
        }
        
        internal static string About_Paragraph_3 {
            get {
                return ResourceManager.GetString("About_Paragraph_3", resourceCulture);
            }
        }
        
        internal static string About_Paragraph_4 {
            get {
                return ResourceManager.GetString("About_Paragraph_4", resourceCulture);
            }
        }
        
        internal static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        internal static string Projects_Itbeard {
            get {
                return ResourceManager.GetString("Projects_Itbeard", resourceCulture);
            }
        }
        
        internal static string Projects_Itbeard_Description {
            get {
                return ResourceManager.GetString("Projects_Itbeard_Description", resourceCulture);
            }
        }
        
        internal static string Projects_CiomnyLos {
            get {
                return ResourceManager.GetString("Projects_CiomnyLos", resourceCulture);
            }
        }
        
        internal static string Projects_CiomnyLos_Description {
            get {
                return ResourceManager.GetString("Projects_CiomnyLos_Description", resourceCulture);
            }
        }
        
        internal static string Projects_KalasyAI {
            get {
                return ResourceManager.GetString("Projects_KalasyAI", resourceCulture);
            }
        }
        
        internal static string Projects_KalasyAI_Description {
            get {
                return ResourceManager.GetString("Projects_KalasyAI_Description", resourceCulture);
            }
        }
        
        internal static string Projects_Aia {
            get {
                return ResourceManager.GetString("Projects_Aia", resourceCulture);
            }
        }
        
        internal static string Projects_Aia_Description {
            get {
                return ResourceManager.GetString("Projects_Aia_Description", resourceCulture);
            }
        }
        
        internal static string Projects_Vkl {
            get {
                return ResourceManager.GetString("Projects_Vkl", resourceCulture);
            }
        }
        
        internal static string Projects_Vkl_Description {
            get {
                return ResourceManager.GetString("Projects_Vkl_Description", resourceCulture);
            }
        }
        
        internal static string Projects_BelarusAi {
            get {
                return ResourceManager.GetString("Projects_BelarusAi", resourceCulture);
            }
        }
        
        internal static string Projects_BelarusAi_Description {
            get {
                return ResourceManager.GetString("Projects_BelarusAi_Description", resourceCulture);
            }
        }
        
        internal static string Projects_EvoCode {
            get {
                return ResourceManager.GetString("Projects_EvoCode", resourceCulture);
            }
        }
        
        internal static string Projects_EvoCode_Description {
            get {
                return ResourceManager.GetString("Projects_EvoCode_Description", resourceCulture);
            }
        }
    }
}
