//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itbeard.Site.WebAssembly.Localizations.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ItbeardShow {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItbeardShow() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Itbeard.Site.WebAssembly.Localizations.Pages.ItbeardShow", typeof(ItbeardShow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        internal static string AboutShow {
            get {
                return ResourceManager.GetString("AboutShow", resourceCulture);
            }
        }
        
        internal static string AboutShow_Paragraph_2 {
            get {
                return ResourceManager.GetString("AboutShow_Paragraph_2", resourceCulture);
            }
        }
        
        internal static string AboutShow_Paragraph_3 {
            get {
                return ResourceManager.GetString("AboutShow_Paragraph_3", resourceCulture);
            }
        }
        
        internal static string Interview {
            get {
                return ResourceManager.GetString("Interview", resourceCulture);
            }
        }
        
        internal static string Interview_Paragraph_1 {
            get {
                return ResourceManager.GetString("Interview_Paragraph_1", resourceCulture);
            }
        }
        
        internal static string Interview_Paragraph_2 {
            get {
                return ResourceManager.GetString("Interview_Paragraph_2", resourceCulture);
            }
        }
        
        internal static string Profession {
            get {
                return ResourceManager.GetString("Profession", resourceCulture);
            }
        }
        
        internal static string Profession_Paragraph_1 {
            get {
                return ResourceManager.GetString("Profession_Paragraph_1", resourceCulture);
            }
        }
        
        internal static string Profession_Paragraph_2 {
            get {
                return ResourceManager.GetString("Profession_Paragraph_2", resourceCulture);
            }
        }
        
        internal static string Programming {
            get {
                return ResourceManager.GetString("Programming", resourceCulture);
            }
        }
        
        internal static string Programming_Paragraph_1 {
            get {
                return ResourceManager.GetString("Programming_Paragraph_1", resourceCulture);
            }
        }
        
        internal static string Programming_Paragraph_2 {
            get {
                return ResourceManager.GetString("Programming_Paragraph_2", resourceCulture);
            }
        }
        
        internal static string Commercial_Title {
            get {
                return ResourceManager.GetString("Commercial_Title", resourceCulture);
            }
        }
        
        internal static string Commercial_Paragraph1_Part1 {
            get {
                return ResourceManager.GetString("Commercial_Paragraph1_Part1", resourceCulture);
            }
        }
        
        internal static string Commercial_Paragraph2_Part1 {
            get {
                return ResourceManager.GetString("Commercial_Paragraph2_Part1", resourceCulture);
            }
        }
        
        internal static string Commercial_Paragraph2_Part2 {
            get {
                return ResourceManager.GetString("Commercial_Paragraph2_Part2", resourceCulture);
            }
        }
        
        internal static string NonCommercial_Title {
            get {
                return ResourceManager.GetString("NonCommercial_Title", resourceCulture);
            }
        }
        
        internal static string NonCommercial_Paragraph1_Part1 {
            get {
                return ResourceManager.GetString("NonCommercial_Paragraph1_Part1", resourceCulture);
            }
        }
        
        internal static string NonCommercial_Paragraph1_Part2 {
            get {
                return ResourceManager.GetString("NonCommercial_Paragraph1_Part2", resourceCulture);
            }
        }
        
        internal static string NonCommercial_Paragraph1_Part3 {
            get {
                return ResourceManager.GetString("NonCommercial_Paragraph1_Part3", resourceCulture);
            }
        }
        
        internal static string YouTube_List_1 {
            get {
                return ResourceManager.GetString("YouTube_List_1", resourceCulture);
            }
        }
        
        internal static string YouTube_List_2 {
            get {
                return ResourceManager.GetString("YouTube_List_2", resourceCulture);
            }
        }
        
        internal static string YouTube_List_3 {
            get {
                return ResourceManager.GetString("YouTube_List_3", resourceCulture);
            }
        }
        
        internal static string YouTube_List_4 {
            get {
                return ResourceManager.GetString("YouTube_List_4", resourceCulture);
            }
        }
        
        internal static string YouTube_List_2_Link {
            get {
                return ResourceManager.GetString("YouTube_List_2_Link", resourceCulture);
            }
        }
        
        internal static string YouTube_List_3_Link {
            get {
                return ResourceManager.GetString("YouTube_List_3_Link", resourceCulture);
            }
        }
        
        internal static string WhereToSee {
            get {
                return ResourceManager.GetString("WhereToSee", resourceCulture);
            }
        }
        
        internal static string WhereToSee_Paragraph_1 {
            get {
                return ResourceManager.GetString("WhereToSee_Paragraph_1", resourceCulture);
            }
        }
        
        internal static string WhereToSee_Paragraph_2 {
            get {
                return ResourceManager.GetString("WhereToSee_Paragraph_2", resourceCulture);
            }
        }
        
        internal static string WhereToSee_Paragraph_3 {
            get {
                return ResourceManager.GetString("WhereToSee_Paragraph_3", resourceCulture);
            }
        }
        
        internal static string WhereToSee_Paragraph_4 {
            get {
                return ResourceManager.GetString("WhereToSee_Paragraph_4", resourceCulture);
            }
        }
        
        internal static string WhereToSee_Paragraph_5 {
            get {
                return ResourceManager.GetString("WhereToSee_Paragraph_5", resourceCulture);
            }
        }
        
        internal static string WhereToSee_Paragraph_6 {
            get {
                return ResourceManager.GetString("WhereToSee_Paragraph_6", resourceCulture);
            }
        }
        
        internal static string WhereToSee_Paragraph_7 {
            get {
                return ResourceManager.GetString("WhereToSee_Paragraph_7", resourceCulture);
            }
        }
        
        internal static string WhereToSee_Paragraph_8 {
            get {
                return ResourceManager.GetString("WhereToSee_Paragraph_8", resourceCulture);
            }
        }
        
        internal static string WhereToSee_Paragraph_9 {
            get {
                return ResourceManager.GetString("WhereToSee_Paragraph_9", resourceCulture);
            }
        }
        
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        internal static string Suport_Paragraph_11 {
            get {
                return ResourceManager.GetString("Suport_Paragraph_11", resourceCulture);
            }
        }
        
        internal static string Suport_Paragraph_12 {
            get {
                return ResourceManager.GetString("Suport_Paragraph_12", resourceCulture);
            }
        }
        
        internal static string Suport_Paragraph_13 {
            get {
                return ResourceManager.GetString("Suport_Paragraph_13", resourceCulture);
            }
        }
        
        internal static string Suport_Paragraph_14 {
            get {
                return ResourceManager.GetString("Suport_Paragraph_14", resourceCulture);
            }
        }
        
        internal static string Suport_Paragraph_15 {
            get {
                return ResourceManager.GetString("Suport_Paragraph_15", resourceCulture);
            }
        }
        
        internal static string Suport_Paragraph_16 {
            get {
                return ResourceManager.GetString("Suport_Paragraph_16", resourceCulture);
            }
        }
        
        internal static string Suport_Paragraph_17 {
            get {
                return ResourceManager.GetString("Suport_Paragraph_17", resourceCulture);
            }
        }
        
        internal static string Suport_Paragraph_21 {
            get {
                return ResourceManager.GetString("Suport_Paragraph_21", resourceCulture);
            }
        }
        
        internal static string Suport_Paragraph_22 {
            get {
                return ResourceManager.GetString("Suport_Paragraph_22", resourceCulture);
            }
        }
        
        internal static string Bonus {
            get {
                return ResourceManager.GetString("Bonus", resourceCulture);
            }
        }
        
        internal static string Bonus_Discord {
            get {
                return ResourceManager.GetString("Bonus_Discord", resourceCulture);
            }
        }
        
        internal static string Bonus_Discord_Paragraph_1 {
            get {
                return ResourceManager.GetString("Bonus_Discord_Paragraph_1", resourceCulture);
            }
        }
        
        internal static string Bonus_Discord_Paragraph_2 {
            get {
                return ResourceManager.GetString("Bonus_Discord_Paragraph_2", resourceCulture);
            }
        }
        
        internal static string Bonus_News {
            get {
                return ResourceManager.GetString("Bonus_News", resourceCulture);
            }
        }
        
        internal static string Bonus_News_Paragraph_1 {
            get {
                return ResourceManager.GetString("Bonus_News_Paragraph_1", resourceCulture);
            }
        }
        
        internal static string Bonus_News_Paragraph_2 {
            get {
                return ResourceManager.GetString("Bonus_News_Paragraph_2", resourceCulture);
            }
        }
        
        internal static string WhatAboutItbeard {
            get {
                return ResourceManager.GetString("WhatAboutItbeard", resourceCulture);
            }
        }
    }
}
