//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itbeard.Site.WebAssembly.Localizations.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ItbeardShow {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItbeardShow() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Itbeard.Site.WebAssembly.Localizations.Pages.ItbeardShow", typeof(ItbeardShow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        internal static string AboutShow {
            get {
                return ResourceManager.GetString("AboutShow", resourceCulture);
            }
        }
        
        internal static string AboutShow_Paragraph_2 {
            get {
                return ResourceManager.GetString("AboutShow_Paragraph_2", resourceCulture);
            }
        }
        
        internal static string AboutShow_Paragraph_3 {
            get {
                return ResourceManager.GetString("AboutShow_Paragraph_3", resourceCulture);
            }
        }
        
        internal static string Interview {
            get {
                return ResourceManager.GetString("Interview", resourceCulture);
            }
        }
        
        internal static string Interview_Paragraph_1 {
            get {
                return ResourceManager.GetString("Interview_Paragraph_1", resourceCulture);
            }
        }
        
        internal static string Interview_Paragraph_1_Button {
            get {
                return ResourceManager.GetString("Interview_Paragraph_1_Button", resourceCulture);
            }
        }
        
        internal static string Profession {
            get {
                return ResourceManager.GetString("Profession", resourceCulture);
            }
        }
        
        internal static string Profession_Paragraph_1 {
            get {
                return ResourceManager.GetString("Profession_Paragraph_1", resourceCulture);
            }
        }
        
        internal static string Profession_Paragraph_1_Button {
            get {
                return ResourceManager.GetString("Profession_Paragraph_1_Button", resourceCulture);
            }
        }
        
        internal static string Programming {
            get {
                return ResourceManager.GetString("Programming", resourceCulture);
            }
        }
        
        internal static string Programming_Paragraph_1 {
            get {
                return ResourceManager.GetString("Programming_Paragraph_1", resourceCulture);
            }
        }
        
        internal static string Programming_Paragraph_1_Button {
            get {
                return ResourceManager.GetString("Programming_Paragraph_1_Button", resourceCulture);
            }
        }
        
        internal static string AboutShow_Paragraph_3_End {
            get {
                return ResourceManager.GetString("AboutShow_Paragraph_3_End", resourceCulture);
            }
        }
        
        internal static string Commercial_Title {
            get {
                return ResourceManager.GetString("Commercial_Title", resourceCulture);
            }
        }
        
        internal static string Commercial_Paragraph1_Part1 {
            get {
                return ResourceManager.GetString("Commercial_Paragraph1_Part1", resourceCulture);
            }
        }
        
        internal static string Commercial_Paragraph2_Part1 {
            get {
                return ResourceManager.GetString("Commercial_Paragraph2_Part1", resourceCulture);
            }
        }
        
        internal static string Commercial_Paragraph2_Part2 {
            get {
                return ResourceManager.GetString("Commercial_Paragraph2_Part2", resourceCulture);
            }
        }
        
        internal static string NonCommercial_Title {
            get {
                return ResourceManager.GetString("NonCommercial_Title", resourceCulture);
            }
        }
        
        internal static string NonCommercial_Paragraph1_Part1 {
            get {
                return ResourceManager.GetString("NonCommercial_Paragraph1_Part1", resourceCulture);
            }
        }
        
        internal static string NonCommercial_Paragraph1_Part2 {
            get {
                return ResourceManager.GetString("NonCommercial_Paragraph1_Part2", resourceCulture);
            }
        }
        
        internal static string NonCommercial_Paragraph1_Part3 {
            get {
                return ResourceManager.GetString("NonCommercial_Paragraph1_Part3", resourceCulture);
            }
        }
    }
}
