//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itbeard.Site.WebAssembly.Localizations.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sponsorship {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sponsorship() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Itbeard.Site.WebAssembly.Localizations.Pages.Sponsorship", typeof(Sponsorship).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        internal static string Video_HowToSupport_Title {
            get {
                return ResourceManager.GetString("Video_HowToSupport_Title", resourceCulture);
            }
        }
        
        internal static string Patreon_Title {
            get {
                return ResourceManager.GetString("Patreon_Title", resourceCulture);
            }
        }
        
        internal static string Patreon_Paragraph_Part_1 {
            get {
                return ResourceManager.GetString("Patreon_Paragraph_Part_1", resourceCulture);
            }
        }
        
        internal static string Crypto_Title {
            get {
                return ResourceManager.GetString("Crypto_Title", resourceCulture);
            }
        }
        
        internal static string Crypto_Paragraph {
            get {
                return ResourceManager.GetString("Crypto_Paragraph", resourceCulture);
            }
        }
        
        internal static string YouTube_Title {
            get {
                return ResourceManager.GetString("YouTube_Title", resourceCulture);
            }
        }
        
        internal static string YouTube_Paragraph_1 {
            get {
                return ResourceManager.GetString("YouTube_Paragraph_1", resourceCulture);
            }
        }
        
        internal static string YouTube_Paragraph_2 {
            get {
                return ResourceManager.GetString("YouTube_Paragraph_2", resourceCulture);
            }
        }
        
        internal static string YouTube_Paragraph_3 {
            get {
                return ResourceManager.GetString("YouTube_Paragraph_3", resourceCulture);
            }
        }
        
        internal static string YouTube_List_1 {
            get {
                return ResourceManager.GetString("YouTube_List_1", resourceCulture);
            }
        }
        
        internal static string YouTube_List_2 {
            get {
                return ResourceManager.GetString("YouTube_List_2", resourceCulture);
            }
        }
        
        internal static string YouTube_List_3 {
            get {
                return ResourceManager.GetString("YouTube_List_3", resourceCulture);
            }
        }
        
        internal static string YouTube_List_4 {
            get {
                return ResourceManager.GetString("YouTube_List_4", resourceCulture);
            }
        }
        
        internal static string YouTube_List_5 {
            get {
                return ResourceManager.GetString("YouTube_List_5", resourceCulture);
            }
        }
        
        internal static string SponsorYoutube_Title {
            get {
                return ResourceManager.GetString("SponsorYoutube_Title", resourceCulture);
            }
        }
        
        internal static string SponsorYoutube_Paragraph_1_Part_1 {
            get {
                return ResourceManager.GetString("SponsorYoutube_Paragraph_1_Part_1", resourceCulture);
            }
        }
        
        internal static string SponsorYoutube_Paragraph_2 {
            get {
                return ResourceManager.GetString("SponsorYoutube_Paragraph_2", resourceCulture);
            }
        }
        
        internal static string SponsorYoutube_Paragraph_3 {
            get {
                return ResourceManager.GetString("SponsorYoutube_Paragraph_3", resourceCulture);
            }
        }
        
        internal static string SponsorYoutube_Paragraph_4 {
            get {
                return ResourceManager.GetString("SponsorYoutube_Paragraph_4", resourceCulture);
            }
        }
        
        internal static string SponsorYoutube_Paragraph_5 {
            get {
                return ResourceManager.GetString("SponsorYoutube_Paragraph_5", resourceCulture);
            }
        }
        
        internal static string SponsorYoutube_Paragraph_5_Link_1 {
            get {
                return ResourceManager.GetString("SponsorYoutube_Paragraph_5_Link_1", resourceCulture);
            }
        }
        
        internal static string SponsorYoutube_Paragraph_5_Link_2 {
            get {
                return ResourceManager.GetString("SponsorYoutube_Paragraph_5_Link_2", resourceCulture);
            }
        }
        
        internal static string SponsorYoutube_Paragraph_5_Link_3 {
            get {
                return ResourceManager.GetString("SponsorYoutube_Paragraph_5_Link_3", resourceCulture);
            }
        }
        
        internal static string Apple_Title {
            get {
                return ResourceManager.GetString("Apple_Title", resourceCulture);
            }
        }
        
        internal static string Apple_Paragraph_Part_1 {
            get {
                return ResourceManager.GetString("Apple_Paragraph_Part_1", resourceCulture);
            }
        }
        
        internal static string Patreon_Paragraph_Part_2 {
            get {
                return ResourceManager.GetString("Patreon_Paragraph_Part_2", resourceCulture);
            }
        }
        
        internal static string Patreon_Paragraph_Part_3 {
            get {
                return ResourceManager.GetString("Patreon_Paragraph_Part_3", resourceCulture);
            }
        }
        
        internal static string Patreon_Paragraph_Part_5 {
            get {
                return ResourceManager.GetString("Patreon_Paragraph_Part_5", resourceCulture);
            }
        }
        
        internal static string Patreon_Paragraph_Part_4 {
            get {
                return ResourceManager.GetString("Patreon_Paragraph_Part_4", resourceCulture);
            }
        }
        
        internal static string YouTube_List_2_Link {
            get {
                return ResourceManager.GetString("YouTube_List_2_Link", resourceCulture);
            }
        }
        
        internal static string YouTube_List_3_Link {
            get {
                return ResourceManager.GetString("YouTube_List_3_Link", resourceCulture);
            }
        }
        
        internal static string SponsorYoutube_Paragraph_1_Part_2 {
            get {
                return ResourceManager.GetString("SponsorYoutube_Paragraph_1_Part_2", resourceCulture);
            }
        }
        
        internal static string SponsorYoutube_Paragraph_1_Part_3 {
            get {
                return ResourceManager.GetString("SponsorYoutube_Paragraph_1_Part_3", resourceCulture);
            }
        }
        
        internal static string SponsorYoutube_Paragraph_1_Part_4 {
            get {
                return ResourceManager.GetString("SponsorYoutube_Paragraph_1_Part_4", resourceCulture);
            }
        }
        
        internal static string Apple_Paragraph_Part_2 {
            get {
                return ResourceManager.GetString("Apple_Paragraph_Part_2", resourceCulture);
            }
        }
        
        internal static string Apple_Paragraph_Part_3 {
            get {
                return ResourceManager.GetString("Apple_Paragraph_Part_3", resourceCulture);
            }
        }
    }
}
