//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itbeard.Site.WebAssembly.Localizations.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Support {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Support() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Itbeard.Site.WebAssembly.Localizations.Pages.Support", typeof(Support).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        internal static string Video_HowToSupport_Title {
            get {
                return ResourceManager.GetString("Video_HowToSupport_Title", resourceCulture);
            }
        }
        
        internal static string Patreon_Title {
            get {
                return ResourceManager.GetString("Patreon_Title", resourceCulture);
            }
        }
        
        internal static string Patreon_Paragraph_Part_1 {
            get {
                return ResourceManager.GetString("Patreon_Paragraph_Part_1", resourceCulture);
            }
        }
        
        internal static string Crypto_Title {
            get {
                return ResourceManager.GetString("Crypto_Title", resourceCulture);
            }
        }
        
        internal static string Crypto_Paragraph {
            get {
                return ResourceManager.GetString("Crypto_Paragraph", resourceCulture);
            }
        }
        
        internal static string Patreon_Paragraph_Part_2 {
            get {
                return ResourceManager.GetString("Patreon_Paragraph_Part_2", resourceCulture);
            }
        }
        
        internal static string Patreon_Paragraph_Part_3 {
            get {
                return ResourceManager.GetString("Patreon_Paragraph_Part_3", resourceCulture);
            }
        }
        
        internal static string Patreon_Paragraph_Part_5 {
            get {
                return ResourceManager.GetString("Patreon_Paragraph_Part_5", resourceCulture);
            }
        }
        
        internal static string Patreon_Paragraph_Part_4 {
            get {
                return ResourceManager.GetString("Patreon_Paragraph_Part_4", resourceCulture);
            }
        }
        
        internal static string Merch {
            get {
                return ResourceManager.GetString("Merch", resourceCulture);
            }
        }
        
        internal static string Merch_Paragraph_11 {
            get {
                return ResourceManager.GetString("Merch_Paragraph_11", resourceCulture);
            }
        }
        
        internal static string Merch_Paragraph_2 {
            get {
                return ResourceManager.GetString("Merch_Paragraph_2", resourceCulture);
            }
        }
        
        internal static string Merch_Paragraph_12 {
            get {
                return ResourceManager.GetString("Merch_Paragraph_12", resourceCulture);
            }
        }
        
        internal static string Merch_Paragraph_13 {
            get {
                return ResourceManager.GetString("Merch_Paragraph_13", resourceCulture);
            }
        }
        
        internal static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        internal static string Card_Paragraph_11 {
            get {
                return ResourceManager.GetString("Card_Paragraph_11", resourceCulture);
            }
        }
        
        internal static string Card_Paragraph_12 {
            get {
                return ResourceManager.GetString("Card_Paragraph_12", resourceCulture);
            }
        }
        
        internal static string Card_Paragraph_13 {
            get {
                return ResourceManager.GetString("Card_Paragraph_13", resourceCulture);
            }
        }
        
        internal static string Card_Paragraph_14 {
            get {
                return ResourceManager.GetString("Card_Paragraph_14", resourceCulture);
            }
        }
        
        internal static string Card_Paragraph_15 {
            get {
                return ResourceManager.GetString("Card_Paragraph_15", resourceCulture);
            }
        }
    }
}
