//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itbeard.Site.WebAssembly.Localizations.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Thanks {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Thanks() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Itbeard.Site.WebAssembly.Localizations.Pages.Thanks", typeof(Thanks).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        internal static string Paragraph {
            get {
                return ResourceManager.GetString("Paragraph", resourceCulture);
            }
        }
        
        internal static string Name1 {
            get {
                return ResourceManager.GetString("Name1", resourceCulture);
            }
        }
        
        internal static string Name2 {
            get {
                return ResourceManager.GetString("Name2", resourceCulture);
            }
        }
        
        internal static string Name3 {
            get {
                return ResourceManager.GetString("Name3", resourceCulture);
            }
        }
        
        internal static string Name4 {
            get {
                return ResourceManager.GetString("Name4", resourceCulture);
            }
        }
        
        internal static string Name5 {
            get {
                return ResourceManager.GetString("Name5", resourceCulture);
            }
        }
        
        internal static string Name6 {
            get {
                return ResourceManager.GetString("Name6", resourceCulture);
            }
        }
        
        internal static string Name7 {
            get {
                return ResourceManager.GetString("Name7", resourceCulture);
            }
        }
    }
}
