name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install WebAssembly Tools workload
        run: dotnet workload install wasm-tools

      - name: Restore workloads
        run: dotnet workload restore --project Site/Itbeard.Site.WebAssembly/Itbeard.Site.WebAssembly.csproj

      - name: Restore NuGet packages
        run: dotnet restore Site/Itbeard.sln

      - name: Build (Release)
        run: dotnet build Site/Itbeard.Site.WebAssembly/Itbeard.Site.WebAssembly.csproj -c Release --no-restore

      - name: Publish (no-build)
        run: dotnet publish Site/Itbeard.Site.WebAssembly/Itbeard.Site.WebAssembly.csproj -c Release -o publish --nologo --no-build

      - name: Add .nojekyll file
        run: touch publish/wwwroot/.nojekyll

      - name: Add CNAME for custom domain
        run: echo "itbeard.com" > publish/wwwroot/CNAME

      - name: Copy index.html to 404.html (if present)
        run: |
          if [ -f publish/wwwroot/index.html ]; then
            cp publish/wwwroot/index.html publish/wwwroot/404.html
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'publish/wwwroot'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

